<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.onsdigital</groupId>
    <artifactId>dp-image-api-client-java</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <java.version>1.8</java.version>
        <encoding>UTF-8</encoding>
        <dp.logging.version>v2.0.0-beta.18</dp.logging.version>
        <jackson.version>2.22.2</jackson.version>
    </properties>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <!-- Keep logging at the beginning of the file so that org.slf4j dependency is imported at its latest version required by logging to work -->
        <dependency>
            <groupId>com.github.onsdigital</groupId>
            <artifactId>dp-logging</artifactId>
            <version>${dp.logging.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents.client5</groupId>
            <artifactId>httpclient5</artifactId>
            <version>5.6.4</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.17.0</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.9.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>4.8.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <version>4.8.0</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>${encoding}</encoding>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.sonatype.ossindex.maven</groupId>
                <artifactId>ossindex-maven-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>audit-dependencies-critical</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>audit</goal>
                        </goals>
                        <!-- configuration for mvn validate -->
                        <configuration>
                            <!-- if CVSS >= 9.0 (critical) then ERROR else WARN -->
                            <fail>true</fail>
                            <cvssScoreThreshold>9.0</cvssScoreThreshold>
                        </configuration>
                    </execution>
                </executions>
                <!-- configuration for mvn ossindex:audit -->
                <configuration>
                    <authId>ossindex</authId>
                    <!-- if CVSS >= 7.0 (high or critical) then ERROR else WARN -->
                    <fail>true</fail>
                    <cvssScoreThreshold>7.0</cvssScoreThreshold>
                    <excludeVulnerabilityIds>
                        <!-- Jira epic to remove the following exclusion: DIS-5085
                         
                          This is to upgrade logback-classic
                        -->
                        <exclude>CVE-2026-13006</exclude>
                    </excludeVulnerabilityIds>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
